//auth actions
export const POST_USER_REQUEST: 'POST_USER_REQUEST' = 'POST_USER_REQUEST';
export const POST_USER_SUCCESS: 'POST_USER_SUCCESS' = 'POST_USER_SUCCESS';
export const POST_USER_FAILED: 'POST_USER_FAILED' = 'POST_USER_FAILED';
export const POST_TOKEN_REQUEST: 'POST_TOKEN_REQUEST' = 'POST_TOKEN_REQUEST';
export const POST_TOKEN_SUCCESS: 'POST_TOKEN_SUCCESS' = 'POST_TOKEN_SUCCESS';
export const POST_TOKEN_FAILED: 'POST_TOKEN_FAILED' = 'POST_TOKEN_FAILED';
export const FORGOT_PSWD_REQUEST: 'FORGOT_PSWD_REQUEST' = 'FORGOT_PSWD_REQUEST';
export const FORGOT_PSWD_SUCCESS: 'FORGOT_PSWD_SUCCESS' = 'FORGOT_PSWD_SUCCESS';
export const FORGOT_PSWD_FAILED: 'FORGOT_PSWD_FAILED' = 'FORGOT_PSWD_FAILED';
export const RESET_PSWD_REQUEST: 'RESET_PSWD_REQUEST' = 'RESET_PSWD_REQUEST';
export const RESET_PSWD_SUCCESS: 'RESET_PSWD_SUCCESS' = 'RESET_PSWD_SUCCESS';
export const RESET_PSWD_FAILED: 'RESET_PSWD_FAILED' = 'RESET_PSWD_FAILED';
export const USER_LOGGED_IN: 'USER_LOGGED_IN' = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT: 'USER_LOGGED_OUT' = 'USER_LOGGED_OUT';

//ingredients actions
export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const SET_ACTIVE_TAB: 'SET_ACTIVE_TAB' = 'SET_ACTIVE_TAB';
export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DEL_INGREDIENT: 'DEL_INGREDIENT' = 'DEL_INGREDIENT';
export const RESET_INGREDIENTS: 'RESET_INGREDIENTS' = 'RESET_INGREDIENTS';
export const SORT_INGREDIENTS: 'SORT_INGREDIENTS' = 'SORT_INGREDIENTS';

//order actions
export const POST_ORDER_REQUEST: 'POST_ORDER_REQUEST' = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS' = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED: 'POST_ORDER_FAILED' = 'POST_ORDER_FAILED';
export const CLOSE_ORDER: 'CLOSE_ORDER' = 'CLOSE_ORDER';